### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by zolzaya** [pbteja1998/remix-auth-google#1]
Hey, 

Thank you for awesome plugin. Can you provide us example source code. I think README is unclear. For example where is the `authenticator` method come from? `import { authenticator } from '~/auth.server'` is it Google Strategy code or not?

**Comment by pbteja1998** [comment]
Hey @zolzaya please also check the README of [remix-auth](https://github.com/sergiodxa/remix-auth). This is meant to be used along with `remix-auth`. It's not a standalone project. You will see the `authenticator` object. Let me know if you still have questions after going through that repo's README.

**Comment by pbteja1998** [comment]
Check this example. `remix-auth-google` will be exactly same as this,. Just replace `github` with `google` everywhere you see it. 

https://github.com/remix-run/remix/tree/main/examples/remix-auth-github

**Comment by vritzka** [comment]
That example has been moved to 

https://github.com/remix-run/examples/tree/main/remix-auth-github

I must say, I'd also really like a better documentation to this.
