### ISSUE TITLE
Remix v2

### ISSUE THREAD

**Issue by nicknikolov** [pbteja1998/remix-auth-google#13]
Hi there?

Would you be able to update your dependency so we can install this package in Remix v2 apps without NPM complaining. Right now we have to use `--legacy-peer-deps`.

Thanks!

**Comment by pbteja1998** [comment]
Hi @nicknikolov can you please open a PR with the relevant changes?

**Comment by pbteja1998** [comment]
@nicknikolov Please try `v1.3.0` and let me know if your problem is solved.

**Comment by nicknikolov** [comment]
Thanks @pbteja1998, seem to be fine now. Appreciate it!
