### ISSUE TITLE
`remix-auth-oauth2` 1.11.0 breaks this library due to this.scope collision

### ISSUE THREAD

**Issue by Hansenq** [pbteja1998/remix-auth-google#14]
`remix-auth-oauth2` version [1.11.0](https://github.com/sergiodxa/remix-auth-oauth2/releases) adds a `this.scope` property to `Oauth2Strategy` as a `string`. This library (`remix-auth-google`) also defines `this.scope` that overrides that one, but it here it's defined as an array. 

In 1.11.0 of `remix-auth-oauth2`, the `scope` value in the Oauth URL parameters is now [directly set](https://github.com/sergiodxa/remix-auth-oauth2/blob/main/src/index.ts#L368) from `this.scope`, rather than using the `authorizationParams` method from the `GoogleStrategy`. However, `this.scope` is an array in `GoogleStrategy` (because it's been overridden), and the `scope` parameter is now serialized as `"openid,email,profile"` (because the default array `toString()` joins with a single comma), rather than the correct `"openid email profile"`. 

As a result, all Google logins after updating `remix-auth-oauth2` are now failing, because google does not recognize the comma as a separator. 

We should update the scope parameter to match the type in the parent `remix-auth-oauth2` library. 

If I have some time later today I'll try opening up a PR

**Comment by Hansenq** [comment]
thanks!

**Comment by pbteja1998** [comment]
@Hansenq published this in `v1.3.0`. I would really appreciate it if you can install that version and let me know if everything looks fine to you.

**Comment by Hansenq** [comment]
it works! Thanks for deploying so quickly
