### ISSUE TITLE
Dynamic successRedirect.

### ISSUE THREAD

**Issue by pkishorez** [pbteja1998/remix-auth-google#3]
How can I redirect the page to the URL that is dynamic?

```
export let loader: LoaderFunction = ({ request, params }) => {
  return authenticator.authenticate("google", request, {
    successRedirect: "/dashboard",
    failureRedirect: "/login",
  });
};
```

Currently, successRedirect is hardcoded to some predefined URL, in this case "/dashboard".
My use case is to redirect to the page, that requested authentication rather than standard dashboard page.

Help appreciated :)

**Comment by pbteja1998** [comment]
@pkishorez this article might help.

https://sergiodxa.com/articles/add-returnto-behavior-to-remix-auth

**Comment by siddharthborderwala** [comment]
Check this out https://github.com/sergiodxa/remix-auth#custom-redirect-url-based-on-the-user

**Comment by jorisre** [comment]
@pkishorez How did you manage the dynamic success redirect?
